# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-on2YJmFwiDcl7pLt5VhNrmQdC1Dbes
"""

pip install faker

"""### Student Performance Analysis"""

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

num_students = 250

student_ids = [f'S{i:03d}' for i in range(1, num_students + 1)]
names = [fake.name() for _ in range(num_students)]
genders = np.random.choice(['Male', 'Female'], num_students)
departments = np.random.choice(['CSE', 'IT', 'ECE'], num_students)
years = np.random.choice(['1st', '2nd', '3rd'], num_students)
maths_marks = np.random.randint(40, 100, num_students)
science_marks = np.random.randint(40, 100, num_students)
english_marks = np.random.randint(40, 100, num_students)
attendance = np.random.randint(50, 101, num_students)
internal_marks = np.random.randint(0, 26, num_students)

students_data = pd.DataFrame({
    'Student_ID': student_ids,
    'Name': names,
    'Gender': genders,
    'Department': departments,
    'Year': years,
    'Maths': maths_marks,
    'Science': science_marks,
    'English': english_marks,
    'Attendance (%)': attendance,
    'Internal Marks': internal_marks
})

display(students_data)



"""### Relationship Between Variables

#### Attendance vs. Average Marks
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Correlation between Attendance and Average Marks
correlation_attendance_marks = students_data['Attendance (%)'].corr(students_data['Average Marks'])
print(f"Correlation between Attendance and Average Marks: {correlation_attendance_marks:.2f}")

# Scatter plot for Attendance vs. Average Marks
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Attendance (%)', y='Average Marks', data=students_data)
plt.title('Attendance (%) vs. Average Marks')
plt.xlabel('Attendance (%)')
plt.ylabel('Average Marks')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""#### Internal Marks vs. Final Performance (Average Marks)"""

# Correlation between Internal Marks and Average Marks
correlation_internal_marks = students_data['Internal Marks'].corr(students_data['Average Marks'])
print(f"Correlation between Internal Marks and Average Marks: {correlation_internal_marks:.2f}")

# Scatter plot for Internal Marks vs. Average Marks
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Internal Marks', y='Average Marks', data=students_data)
plt.title('Internal Marks vs. Average Marks (Final Performance)')
plt.xlabel('Internal Marks')
plt.ylabel('Average Marks')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

print("\nDepartment-wise Average Marks and Grade Distribution:")
display(students_data.groupby('Department')['Average Marks'].describe())
display(students_data.groupby('Department')['Grade'].value_counts(normalize=True).unstack(fill_value=0).mul(100).round(2))

"""### Data Visualizations: Graphs and Charts

#### 1. Grade Distribution (Pie Chart)
"""

grade_counts = students_data['Grade'].value_counts().sort_index()

plt.figure(figsize=(8, 8))
plt.pie(grade_counts, labels=grade_counts.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.Paired.colors)
plt.title('Distribution of Grades Among Students')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""#### 2. Department-wise Average Marks (Bar Chart)"""

dept_avg_marks = students_data.groupby('Department')['Average Marks'].mean().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=dept_avg_marks.index, y=dept_avg_marks.values, palette='viridis')
plt.title('Average Marks by Department')
plt.xlabel('Department')
plt.ylabel('Average Marks')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""#### 3. Gender-wise Average Marks (Bar Chart)"""

gender_avg_marks = students_data.groupby('Gender')['Average Marks'].mean().sort_values(ascending=False)

plt.figure(figsize=(8, 6))
sns.barplot(x=gender_avg_marks.index, y=gender_avg_marks.values, palette='coolwarm')
plt.title('Average Marks by Gender')
plt.xlabel('Gender')
plt.ylabel('Average Marks')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""#### 4. Histograms for Subject Marks Distribution"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)
fig.suptitle('Distribution of Marks in Core Subjects')

sns.histplot(students_data['Maths'], bins=10, kde=True, ax=axes[0], color='skyblue')
axes[0].set_title('Maths Marks')
axes[0].set_xlabel('Marks')
axes[0].set_ylabel('Number of Students')

sns.histplot(students_data['Science'], bins=10, kde=True, ax=axes[1], color='lightcoral')
axes[1].set_title('Science Marks')
axes[1].set_xlabel('Marks')

sns.histplot(students_data['English'], bins=10, kde=True, ax=axes[2], color='lightgreen')
axes[2].set_title('English Marks')
axes[2].set_xlabel('Marks')

plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent suptitle overlap
plt.show()

"""#### 5. Histogram for Attendance Distribution"""

plt.figure(figsize=(10, 6))
sns.histplot(students_data['Attendance (%)'], bins=10, kde=True, color='purple')
plt.title('Distribution of Student Attendance (%)')
plt.xlabel('Attendance (%)')
plt.ylabel('Number of Students')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("\nGender-wise Average Marks and Grade Distribution:")
display(students_data.groupby('Gender')['Average Marks'].describe())
display(students_data.groupby('Gender')['Grade'].value_counts(normalize=True).unstack(fill_value=0).mul(100).round(2))

"""#### Year-wise Trends"""

print("\nYear-wise Average Marks and Grade Distribution:")
display(students_data.groupby('Year')['Average Marks'].describe())
display(students_data.groupby('Year')['Grade'].value_counts(normalize=True).unstack(fill_value=0).mul(100).round(2))



import random

print(random.randint(1, 5))   # 1,2,3,4,5
print(random.randrange(1, 5)) # 1,2,3,4
print(random.randrange(1, 10, 2)) # 1,3,5,7,9

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

num_students = 250

student_ids = [f'S{i:03d}' for i in range(1, num_students + 1)]
names = [fake.name() for _ in range(num_students)]
genders = np.random.choice(['Male', 'Female'], num_students)
departments = np.random.choice(['CSE', 'IT', 'ECE'], num_students)
years = np.random.choice(['1st', '2nd', '3rd'], num_students)
maths_marks = np.random.randint(40, 100, num_students)
science_marks = np.random.randint(40, 100, num_students)
english_marks = np.random.randint(40, 100, num_students)
attendance = np.random.randint(50, 101, num_students)
internal_marks = np.random.randint(0, 26, num_students)

students_data = pd.DataFrame({
    'Student_ID': student_ids,
    'Name': names,
    'Gender': genders,
    'Department': departments,
    'Year': years,
    'Maths': maths_marks,
    'Science': science_marks,
    'English': english_marks,
    'Attendance (%)': attendance,
    'Internal Marks': internal_marks
})

students_data['Total Marks'] = students_data['Maths'] + students_data['Science'] + students_data['English']
students_data['Average Marks'] = students_data['Total Marks'] / 3
bins = [0, 60, 70, 80, 90, 100]
labels = ['F', 'D', 'C', 'B', 'A']
students_data['Grade'] = pd.cut(students_data['Average Marks'], bins=bins, labels=labels, right=False)

print("\nDescriptive statistics for Total Marks and Average Marks:")
display(students_data[['Total Marks', 'Average Marks']].describe())

print("\nGrade Distribution:")
display(students_data['Grade'].value_counts())

missing_values = students_data.isnull().sum()
print("Missing values per column:")
print(missing_values)

students_data.info()

numerical_columns = ['Maths', 'Science', 'English', 'Attendance (%)', 'Internal Marks']

print("\nDescriptive statistics for numerical columns:")
display(students_data[numerical_columns].describe())

print("\nMode for each numerical column:")
for col in numerical_columns:
    print(f"Mode of {col}:\n{students_data[col].mode()}\n")

students_data['Total Marks'] = students_data['Maths'] + students_data['Science'] + students_data['English']
display(students_data.head())

students_data['Average Marks'] = students_data['Total Marks'] / 3
display(students_data.head())

bins = [0, 60, 70, 80, 90, 100]
labels = ['F', 'D', 'C', 'B', 'A']

students_data['Grade'] = pd.cut(students_data['Average Marks'], bins=bins, labels=labels, right=False)
display(students_data.head())

print("\nGrade Distribution:")
display(students_data['Grade'].value_counts())

print("\nDescriptive statistics for Total Marks and Average Marks:")
display(students_data[['Total Marks', 'Average Marks']].describe())